### ISSUE TITLE
25% off IDA Home and 10% off IDA Pro

### ISSUE THREAD

**Issue by neon-schedule** [0x90n/InfoSec-Black-Friday#115]
25% off IDA Home and 10% off IDA Pro

https://hex-rays.com/terms-and-conditions-black-friday-sale-2022/

From: 2:01 am (CET) Friday, 25th November,
To:  11:59 pm (CET) November 28th, 2022.

**Comment by 0x90n** [comment]
Added! Thanks a bunch for sharing this
