### ISSUE TITLE
BusKill 10% off

### ISSUE THREAD

**Issue by maltfield** [0x90n/InfoSec-Black-Friday#164]
Please add the following to your "hardware" section

```
BusKill (Magnetic Breakaway Dead Man Switch)
https://buskill.in/
Get 10% off all orders paid with cryptocurrency
Deal ends: Dec 04
```

#### The Deal

BusKill's black friday deal is 10% off all products purchased between Nov 19 to Dec 04 2022.

No code is needed. The total will be reduced by 10% at checkout for all orders paid with cryptocurrencies.

 * https://www.buskill.in/bitcoin-black-friday-2022/

#### What is BusKill? How is it InfoSec Related?

BusKill is an open-source hardware and software project that uses a hardware tripwire/dead-man-switch (a usb cable with a magnetic breakaway) to trigger your computer to lock or shutdown if the user is physically separated from their machine.

 * https://en.wikipedia.org/wiki/BusKill

The following guide describes how BusKill can be configured to wipe the LUKS Header (containing the FDE key) and its metadata. It shows a video demo where the machine wiped the keys & powered-off in <6 seconds, and it includes a post-execution forensic analysis in Kali with bulk_extractor

 * https://www.buskill.in/luks-self-destruct/

**Comment by 0x90n** [comment]
Added!
