### ISSUE TITLE
Will there be a 2023 edition? Or should we make a fork?

### ISSUE THREAD

**Issue by PfiatDe** [0x90n/InfoSec-Black-Friday#184]
Will there be a 2023 edition? Or should we make a fork?
The last github activity from 0x90n is a year ago :'( , however asked on twitter.
I would always prefer to stay here, but before we get nothing we can do a fork.

Maybe here?
https://github.com/CriimBow/InfoSec-Black-Friday

Opinions?

**Comment by JulianGR** [comment]
yes please, let's condense all efforts to that repo
