### ISSUE TITLE
CCNA, CEH, OSCP, CISSP

### ISSUE THREAD

**Issue by TheDeveloperTom** [0x90n/InfoSec-Black-Friday#213]
Hi there! Would be so cool if you find some discounts for a course/voucher for these certificates: CCNA, CEH, OSCP, CISSP

**Comment by 0x90n** [comment]
Discounts have been provided for OSCP and CISSP already with their respective vendors. CCNA is not categorized as infosec, more networking; will keep an eye out for others!

**Comment by TheDeveloperTom** [comment]
@0x90n Could you please also point out where have you found OSCP and CISSP discounts? Would be grateful
