### ISSUE TITLE
TCM Security - Deal has Started 

### ISSUE THREAD

**Issue by RiteshSec** [0x90n/InfoSec-Black-Friday#215]
TCM Security Certification & Courses 🙈
https://tcm-sec.com/
(1) 20% off of certifications and live trainings
(2) 50% off of the first payment of the All-Access Membership (any plan)
Code: GobbleGobble23
Deal yet to start

![image](https://github.com/0x90n/InfoSec-Black-Friday/assets/110530131/f28eb55a-2087-410b-90b2-bf09ea268086)

Got the above mail today. Was able to apply the code and get the offer on "PNPT Exam Attempt - with Training".

Please update

**Comment by 0x90n** [comment]
Thanks! Updated
