### ISSUE TITLE
Pulsedive deal update

### ISSUE THREAD

**Issue by euphoricfall** [0x90n/InfoSec-Black-Friday#221]
Updated details for Pulsedive
Link: https://pulsedive.com/pro
Ends 28th Nov

Updated entry:

Pulsedive Threat Intelligence 🙈
https://pulsedive.com/pro
50% off 6 months of Pro with code: BLACKFRIDAY23
Deal ends: 28th November

**Comment by 0x90n** [comment]
Thanks! Updated
