### ISSUE TITLE
ItProTV

### ISSUE THREAD

**Issue by Jopa0226** [0x90n/InfoSec-Black-Friday#31]
Code CYBER50 for 50% off an annual subscription until the 30th

**Comment by 0x90n** [comment]
I had a look through the courses and didn't seem to be InfoSec related - let me know if this is incorrect, but leaving it out for now.

**Comment by Jopa0226** [comment]
They are general IT courses, but also cover Security+, CEH, CISSP, etc.
Therefore they are "loosely" InfoSec related
