### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by chandrabosep** [0x90n/InfoSec-Black-Friday#59]
Hey guys,

Why don't you add some pictures below the products 🖼

I can help you with them 😁

**Comment by 0x90n** [comment]
My preference is to keep it short and snappy like one of my 9000+ Notepad++ tabs, but open to suggestions.

I feel images might make it look like a salesy, bloated page - happy to run a poll though 👯

**Comment by 0x90n** [comment]
Hey @chandrabosep - whilst I really appreciate the effort you went to in adding images etc, looks like we'll keep it text-only for now.
