### ISSUE TITLE
discount query on sn1persecurity

### ISSUE THREAD

**Issue by anantshri** [0x90n/InfoSec-Black-Friday#75]
Opensource project github page lists different price in image ![image](https://user-images.githubusercontent.com/236843/143304037-f496cf98-7c6c-4900-8beb-bc115ef27d65.png)

website right now shows bumped up prices 
![image](https://user-images.githubusercontent.com/236843/143304231-d463be00-f72d-47ff-8e4b-4f3adbd2ac72.png)

Both descriptions point to same version. seems like prices jacked up recently.

**Comment by 0x90n** [comment]
Good pickup. It's not unheard of for price increases of new versions + addons, but is there any way you can find the last date it was the old prices? And if there was any metadata/description changes in the meantime?

Will DM the author of the tool/PR also

**Comment by anantshri** [comment]
Thats exactly what i am pointing the version + addons is exactly the same in both images. github image is 2 months old.

https://web.archive.org/web/20211004194634/https://sn1persecurity.com/wordpress/ is 4th October 2021 entry on official website as captured by web archive. again same rate as github screenshot above.

**Comment by 0x90n** [comment]
Thanks for highlighting that - still waiting back on comms from them, but have removed for now

**Comment by 1N3** [comment]
The Sn1per Professional Elite bundle offered back in October is not the same one we currently have on sale for Black Friday. Our Sn1per Professional Elite bundle was recently revamped to include the MassPwn Add-on as well as the second generation Nessus Add-on we just released. See here for more details: https://sn1persecurity.com/wordpress/product/sn1per-professional-v9-0-elite-bundle-v2/

Neither of the screenshots referenced in this post reflect our Black Friday Special. 

For all questions/concerns regarding our Black Friday Special, please email support@sn1persecurity.com. We would appreciate it if you could update the title of this post as this is NOT a "fake discount".

**Comment by 0x90n** [comment]
Thank you for providing this information and detail 1N3 - it all checks out to me on comparing the differences now.
